---

- name: Execute NTP config on IOS systems
  ansible.builtin.import_tasks: ios-ntp-config.yml
  when:
    - ansible_network_os is defined
    - ansible_network_os == 'ios'

# - name: Execute NTP config on NXOS systems
#   ansible.builtin.import_tasks: nxos-ntp-config.yml
#   when:
#     - ansible_network_os is defined
#     - ansible_network_os == 'nxos'
